db = "../reports/report_solved4.sqlite"
p = 0.90

[replace_path_prefix]
"/local/home/jordanpa/" = "../../"

[ignore]
constructors = false
destructors = true
path_prefix = [
  "/local/home/jordanpa/cvc5-repo/build/"
]

# TODO: Investigate where the consistent offset comes from
[path."/local/home/jordanpa/cvc5-repo/src/theory/theory_engine.cpp"]
ignore = {this = true}

[path."/local/home/jordanpa/cvc5-repo/src/api/cpp/cvc5.cpp"]
line_ranges = [ 
 [7743, 7839]
]

