db = "./reports/report.sqlite"
p = 0.75

# placeholder = "std::cout << \"Unsupported feature\" << std::endl; exit(1000); __builtin_unreachable();"
placeholder = "std::cout << \"Unsupported feature\" << std::endl; exit(1000);"
imports = ["#include <iostream>", "#include <cstdlib>"]

[replace_path_prefix]
"/local/home/jordanpa/" = "../../"
